### ISSUE TITLE
config should be a global constant

### ISSUE THREAD

**Issue by martindemello** [domino14/macondo#107]
We currently pass the config struct around all over the code; however, it contains paths to resources and as such is a property of the local environment, not a runtime variable. It should therefore be read once at start time, and stored as a single globally accessible read-only variable thereafter.

Note that the sole reason it needs to be passed up and down the entire stack is to load files in the event of their not being cached.

**Comment by martindemello** [comment]
any thoughts on this? i'll do the work for it if you think it's a good idea

**Comment by andy-k** [comment]
wouldn't having _less_ globals be better?

would it work if: functions don't take Config and don't load stuffs from filesystem. but they don't refer to global variables either. instead, they take a struct of pointers to preprocessed objects. (basically a simplified config that's very different from the current Config.) so the caller calls separate functions to parse CSW19.gaddag, leaves.idx, and whatever else into objects, and then when constructing the instance that can generate moves, pass a struct that points to those objects directly instead of by name. it's up to the caller to keep the objects somewhere for reuse if desired (for example it can load NWL18 and reuse the same leaves.idx). each package (analyzer, runner, etc.) will be instantiated with a (different) package-specific subset of the config (there is no master Config struct), and will operate independently thereafter using that one config. if we have two goroutines analyzing a CSW19 and an NWL18 game, they'd just be totally independent instances instantiated from two separate structs. there is no lookup by name (for example, "generateMoves" will not depend on the game lexicon, it will just use the gaddag that's given). all loaders take io.Reader (so they can read from file or []byte) and will always reload (they don't interact with any cache, and they don't populate cache either). it's up to the caller to open/close any file or to cache.

**Comment by martindemello** [comment]
well, having less global *variables* is always good; for global *constants* there are far fewer down sides because you don't need to care about who might be modifying them, they are presumably the same resource every time, and we aren't doing any sort of dependency injection for testing etc.

loading all resources up front and passing a resource struct around is not a bad idea either; in some ways it would make the code cleaner because it's very clear what dependencies everything has, though on the other hand it is going to lead to the struct being passed around everywhere and cluttering up function signatures. it would definitely be better than what we have now though.

**Comment by domino14** [comment]
i believe we have a master config struct now
