### ISSUE TITLE
add a network server interface

### ISSUE THREAD

**Issue by martindemello** [domino14/macondo#63]
This could be done relatively easily by refactoring `shell.go` into functions that always return a value to be displayed rather than displaying it, and have the main loop call `ShowMessage` or `ShowError` on the return value. Then a server module could reuse the code but accept incoming commands over the network, call the shell functions and push the retun value back out.

This would make it possible to use macondo as a language-agnostic "library", programs could launch a macondo server subprocess and communicate with it over ipc.

**Comment by martindemello** [comment]
i can work on this if you like the basic idea.

**Comment by domino14** [comment]
hey @martindemello this is a cool idea. I had thought of the same when I was trying to figure out how to interface `macondo` with the `liwords` repo (macondo basically implements the rules, and later will be used for AI stuff) but decided since they're both Go-based, that I would just include macondo as a library.

However, I still think it would be a good idea. If you want to tackle it, I would ask that you use protobuf as much as possible (see `macondo.proto`) to define the messages and services, and I like Twirp for the RPC framework, unless you really prefer gRPC (I haven't used the latter, but Twirp is reasonably easy to use and I've used it for a few other projects).

**Comment by martindemello** [comment]
sounds good :) i had been thinking of 0mq for the network layer, but rpc over twirp sounds like a good option too. (no particular opinions of twirp vs grpc, except neither of them have ocaml bindings, which makes me sad!)

**Comment by martindemello** [comment]
closing this since we went with a stateless bot interface instead and it might make more sense to let stateful server code be its own repo, possibly extracted out of liwords.
